# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
staticman_url: https://slimentology.herokuapp.com/v2/entry/QueenSlime/slimentology.com/master/comments

# reCaptcha configuration info: the exact same site key and *encrypted* secret that you used in staticman.yml
# I personally don't think the secret needs to be included in the generated site, but the staticman API bridge uses
# it to ensure the site configuration and bridge configuration match (but why not just compare the site key?)
reCaptcha:
  siteKey: 6LcrBboZAAAAAGwS0hzoicHL_VVqafKfI9hzwUDT
  secret: muBO3643CoBEttJXqSobOHGGs9C46OZvjVQHRUOu7z/eZ58GlDRP4LrE1V3IJb1w3Z3uW0m0UrsFiTr6gdKmLdu3ly0x1u/0dUBLr2CnDW0LmVIrFxyxKacVaehXy5yrJa5o2wEJLVQKeIgb0MiNvcx2FLlxthbr3ZTUB/sKTIFQPad8O8xhJsLGO8loqo0xLv7C2HDTLjI/ntj0w3PLJwnF2e5/DC+NdjET0kfJHyxMINeP84RxEqpEqDUKS7qiOxF72FrqHmqaCtbUiC7YhbTP3IH7mP9gxHbn2z4WG1JcMqjFxhp9C0fCv3/EP6VcOX9ZHCtMkYny7ZROl2FGkaNWqAl6URkFvEU47V+5lxLVi3P+mq/ESFP0vJc3AL44FqDif3i+BKYnVNJ9UH7lXWOrx1/1dDXeK/+j7JMbxZoWZdSuyySvzSJqdNNpm9yXSqfW0YVMoG/vZkM5VX2xkp869TH4GjwLYW5iJedgtl5svcXlIg5RkXRiLjbDvChqsdOaayY4hGiEEZ+YfHVkveHmueSqumu5fA/xWHo+tKjEgc9xeeqYgV6sWkalninjE6EGUx+iPOXitehx5hO+fZw7QbX7/qXxK9eVxuaPC3Kk62/gwmgkX+VMszOBjNYTHFW1NJXn4550ebT/fJZT3QKpIcBCh4akUwXGezPZq68=