# Academic Website Builder
# https://sourcethemes.com/academic/
#
# The presence of this file is for compatibility with Blogdown and Forestry.
# If you are not using those tools, this file may be deleted.
#
# The actual configuration files are stored in the `config/_default/` folder.

[params.staticman]
    endpoint = "https://slimentology.herokuapp.com/v2/entry"
    username = "QueenSlime"
    repository = "slimentology.com"
    branch = "development"